"""
Django settings for timi project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

from django.conf import settings
from django.urls import reverse_lazy
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LOGS_DIR = os.path.join(BASE_DIR, 'logs')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c+#1uz0cnynqqu4988jj+hy^#^p7hdje@@@g-=ni@6i9145-tz'

try:
    owner = __file__.split('/')[2].lower()
except:
    owner = __file__.split('\\')[2].lower()

devs = ['edgam', 'mahome']
WHICH = '{}_settings'.format(owner) if owner in devs else 'prod_settings'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'core.apps.CoreConfig',
    # 3rd party
    'corsheaders',
    # 'subdomains',
    'channels',
    'mathfilters',
    'tinymce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # 'subdomains.middleware.SubdomainURLRoutingMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    # 3rd party
    'core.middleware.UserRestrict',
    'core.middleware.ActiveUserMiddleware',
]

SITE_ID = 1

ROOT_URLCONF = 'timi.main_urls'

# SUBDOMAIN_URLCONFS = {
#     None: 'timi.main_urls',
#     'www': 'timi.main_urls',
# }

TEMPLATES_DIRS = [os.path.join(BASE_DIR, 'core/templates')]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMPLATES_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 3rd party
                'core.context_processors.default',
            ],
        },
    },
]

WSGI_APPLICATION = 'timi.wsgi.application'

ASGI_APPLICATION = 'timi.routing.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

MESSAGE_LEVEL = 10

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'core.User'

AUTHENTICATION_BACKENDS = (
    'core.authentication.CustomAuthBackend',
)

PASSWORD_RESET_TIMEOUT_DAYS = 1

# CSRF_FAILURE_VIEW = 'core.views.csrf_failure'

# LOGIN_URL = reverse_lazy('authentication', kwargs={'target': 'login'})

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_L10N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "core/static"),
]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Setup caching per Django docs. In actuality, you'd probably use memcached instead of local memory.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': '127.0.0.1:11211'
    }
}

# Number of seconds of inactivity before a user is marked offline
USER_ONLINE_TIMEOUT = 300

# Number of seconds that we will keep track of inactive users for before
# their last seen is removed from the cache
USER_LASTSEEN_TIMEOUT = 60 * 60 * 24 * 7

DATA_UPLOAD_MAX_MEMORY_SIZE = None
FILE_UPLOAD_MAX_MEMORY_SIZE = 20971520

UPLOADS_DIR = os.path.join(MEDIA_ROOT, 'uploads')

FILEBROWSER_DIRECTORY = ''
DIRECTORY = ''

TINYMCE_JS_URL = os.path.join(STATIC_URL, "modules/tinymce/tinymce.min.js")
TINYMCE_JS_ROOT = os.path.join(STATIC_ROOT, "modules/tinymce/")
# TINYMCE_FILEBROWSER = True
TINYMCE_DEFAULT_CONFIG = {
    'referrer_policy': 'origin',
    # 'icons_url': 'https://www.example.com/icons/material/icons.js',
    # 'icons': 'material',
    'height': 500,
    'plugins': "autosave,advlist,charmap,codesample,code,image,imagetools,media,lists,preview,print,table,spellchecker,"
               "paste,searchreplace,pagebreak,wordcount,visualblocks,visualchars,emoticons,autolink,link",
    'toolbar1': 'undo redo|fontsizeselect forecolor styleselect|bold italic underline|'
                'alignjustify alignleft aligncenter alignright alignnone|indent outdent|bullist numlist|',
    'toolbar2': 'code charmap emoticons|image media link|rotateleft rotateright|flipv fliph|editimage imageoptions|preview print|'
                'pagebreak|wordcount visualblocks visualchars',
    'toolbar_mode': 'sliding',
    'toolbar_sticky': True,
    # 'contextmenu_never_use_native': True,
    'theme': "silver",
    'skin': 'oxide',
    'custom_undo_redo_levels': 10,
    'placeholder': "Start editing. . .",
    # 'imagetools_cors_hosts': ['embed-systems.com', 'embedsystem.com.ng'],
    # # 'imagetools_proxy': 'proxy.php',
    # 'file_picker_types': 'file image media',
    # 'file_browser_callback': function(callback, value, meta) {return},
    'image_list': "/upload/",
    'image_advtab': True,
    'image_description': True,
    'image_title': True,
    'image_uploadtab': True,
    'image_prepend_url': MEDIA_URL,
    'images_upload_url': '/upload/',
    'images_upload_base_path': UPLOADS_DIR,
    # 'menu': {
    #     'file': {'title': 'File', 'items': 'newdocument restoredraft | preview | print '},
    #     'edit': {'title': 'Edit', 'items': 'undo redo | cut copy paste | selectall | searchreplace'},
    #     'view': {'title': 'View',
    #              'items': 'code | visualaid visualchars visualblocks | spellchecker | preview fullscreen'},
    #     'insert': {'title': 'Insert',
    #                'items': 'image link media template codesample inserttable | charmap emoticons hr | pagebreak nonbreaking anchor toc | insertdatetime'},
    #     'format': {'title': 'Format',
    #                'items': 'bold italic underline strikethrough superscript subscript codeformat | formats blockformats fontformats fontsizes align | forecolor backcolor | removeformat'},
    #     'tools': {'title': 'Tools', 'items': 'spellchecker spellcheckerlanguage | code wordcount'},
    #     'table': {'title': 'Table', 'items': 'inserttable | cell row column | tableprops deletetable'},
    #     'help': {'title': 'Help', 'items': 'help'}
    # },
    # 'menubar': 'file edit insert view format table tools help',
    # 'mobile': {
    #     'plugins': ['autosave', 'lists', 'autolink'],
    #     'toolbar': ['undo', 'bold', 'italic', 'styleselect']
    # },
}
# TINYMCE_EXTRA_MEDIA = {
#     'css': {
#         'all': [
#             ...
#         ],
#     },
#     'js': [
#         ...
#     ],
# }
