# Generated by Django 2.2.10 on 2020-04-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Embed Systems', max_length=50)),
                ('number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='A brief description of what the company is about')),
                ('site', models.OneToOneField(db_column='site', on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_type', models.IntegerField(choices=[(0, 'Instagram'), (1, 'Facebook'), (2, 'Twitter'), (3, 'Youtube')])),
                ('handle', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('setting', models.ForeignKey(db_column='setting', on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='core.Setting')),
            ],
            options={
                'db_table': 'social_media',
            },
        ),
    ]
