# Generated by Django 2.2.10 on 2020-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setting_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='logo_default',
            field=models.ImageField(blank=True, null=True, upload_to='settings/logo/', verbose_name='Dark Logo Version'),
        ),
        migrations.AddField(
            model_name='setting',
            name='logo_light',
            field=models.ImageField(blank=True, null=True, upload_to='settings/logo/', verbose_name='White Logo Version'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/favicon/', verbose_name='Icon that shows on browser tabs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Superuser'), (1, 'Admin'), (2, 'Blogger'), (3, 'User')], null=True),
        ),
    ]
