# Generated by Django 2.2.10 on 2020-04-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200426_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='index_page_background',
            field=models.ImageField(blank=True, null=True, upload_to='settings/index/', verbose_name='Index: Background image'),
        ),
    ]
