# Generated by Django 2.2.10 on 2020-04-26 14:03

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200426_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about_page_photo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/about/', verbose_name='About Page: CEO image'),
        ),
        migrations.AddField(
            model_name='setting',
            name='about_page_quote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='About Page: CEO quote'),
        ),
        migrations.AddField(
            model_name='setting',
            name='about_page_text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='About Page: CEO text'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='index_page_background',
            field=models.ImageField(blank=True, null=True, upload_to='settings/index/', verbose_name='Index Page: Background image'),
        ),
    ]
