# Generated by Django 2.2.10 on 2020-04-27 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200426_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of the service')),
                ('sub_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sub title of the service')),
                ('image', models.ImageField(upload_to='services/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'service',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.AddField(
            model_name='setting',
            name='services_page_text',
            field=models.TextField(blank=True, null=True, verbose_name='Services Page: Text'),
        ),
        migrations.AddField(
            model_name='service',
            name='setting',
            field=models.ForeignKey(db_column='setting', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.Setting'),
        ),
    ]
