# Generated by Django 3.1 on 2020-08-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200427_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='first_slider_content',
            field=models.CharField(help_text='Slider 1 content', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='first_slider_title',
            field=models.CharField(help_text='Slider 1 title', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='second_slider_content',
            field=models.CharField(help_text='Slider 2 content', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='second_slider_title',
            field=models.CharField(help_text='Slider 2 title', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='third_slider_content',
            field=models.CharField(help_text='Slider 3 content', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='third_slider_title',
            field=models.CharField(help_text='Slider 3 title', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
