# Generated by Django 3.1 on 2020-08-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200822_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='services_page_text',
        ),
        migrations.AddField(
            model_name='setting',
            name='service_text',
            field=models.TextField(blank=True, null=True, verbose_name='Home Page: What we do text'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='first_slider_content',
            field=models.CharField(blank=True, help_text='Slider 1 content', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='first_slider_title',
            field=models.CharField(blank=True, help_text='Slider 1 title', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='second_slider_content',
            field=models.CharField(blank=True, help_text='Slider 2 content', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='second_slider_title',
            field=models.CharField(blank=True, help_text='Slider 2 title', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='third_slider_content',
            field=models.CharField(blank=True, help_text='Slider 3 content', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='third_slider_title',
            field=models.CharField(blank=True, help_text='Slider 3 title', max_length=30, null=True),
        ),
    ]
